openapi: 3.1.0

###############
## Meta info ##
###############
info:
  title: WASAPhotoAPI
  version: 1.0.0
  description: |-
    API for the WASAPhoto application. <br>
    The API follows the CRUD philosophy, that maps HTTP methods TK

tags:
  - name: Authorization
    description: |-
      Endpoints that require the user to be logged in.
      The user must provide his username in the `Authorization` header.
  - name: NoAuth
    description: |-
      Endpoints that don't require the user to be logged in.

###############
## Endpoints ##
###############
paths:

  /me/feed:
    patch:
      operationId: getMyStream
      summary: Returns a list of posts made by the users the current user is following
      tags: ['Authorization']
      responses:
        '200':
          $ref: '#/components/responses/MultiUserPost'
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'

  /me/change_username:
    post:
      operationId: setMyUserName
      summary: Changes the user's username
      tags: ['Authorization']
      description: |-
        Changes the user's username; if the username is already taken an error is returned.
        The previous username won't be reserved and it will be available to other users for the taking.
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                username:
                  $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: Username changed correctly
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '403':
          description: The chosen username is already taken

  /me/followed_users:
    get:
      operationId: getFollowedUsers
      summary: Returns a list of users the current user is following
      tags: ['Authorization']
      responses:
        '200':
          description: List retrieved correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameList'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /me/followed_users/{username}:
    put:
      operationId: followUser
      summary: Adds a specified user to the list of followed users.
      tags: ['Authorization']
      description: |-
        Adds a specified user to the list of followed users.
        If the specified user is already in the list,
        the response will be as if the specified user wasn't in the list before (i.e. 200).
      parameters:
        - $ref: '#/components/parameters/pathUsername'
      responses:
        '200':
          $ref: '#/components/responses/200-Success'
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
    delete:
      operationId: unfollowUser
      summary: Removes a user from the list of followed users.
      tags: ['Authorization']
      description: |-
        Removes the specified user from the current user's list of followed users.
        If the specified user isn't in the list,
        the response will be as if the specified user has been removed correctly (i.e. 200).
      parameters:
        - $ref: '#/components/parameters/pathUsername'
      responses:
        '200':
          $ref: '#/components/responses/200-Success'
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /me/banned_users:
    get:
      operationId: getBannedUsers
      summary: Returns a list of users the current user has banned
      tags: ['Authorization']
      responses:
        '200':
          description: List retrieved correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameList'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /me/banned_users/{username}:
    put:
      operationId: banUser
      summary: Bans a user from seeing the current user's content.
      tags: ['Authorization']
      description: |-
        Adds the specified user to the current user's list of banned users.
      parameters:
        - $ref: '#/components/parameters/pathUsername'
      responses:
        '200':
          $ref: '#/components/responses/200-Success'
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
    delete:
      operationId: unbanUser
      summary: Removes a user from the list of banned users.
      tags: ['Authorization']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
      description: |-
        Removes the specified user from the list of followed users.
        If the specified user doesn't belong to the list,
        the response will be as if the specified user would have been removed correctly (i.e. 200).
      responses:
        '200':
          $ref: '#/components/responses/200-Success'
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /users/{username}:
    get:
      operationId: getUserProfile
      summary: Returns the details about a user's profile
      tags: ['NoAuth']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
      responses:
        '200':
          description: Information retrieved correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /users/{username}/feed:
    get:
      operationId: getUserFeed
      summary: Returns a list of posts made by the user
      tags: ['NoAuth']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
      responses:
        '200':
          $ref: '#/components/responses/MultiUserPost'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /users/{username}/feed/{post_id}:
    get:
      operationId: getUserPost
      summary: Returns details about a single post made by the user
      tags: ['NoAuth']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
        - $ref: '#/components/parameters/pathPostId'
      responses:
        '200':
          $ref: '#/components/responses/MonoUserPost'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /users/{username}/feed/{post_id}/likes:
    get:
      operationId: getUserPostLikes
      summary: Returns a list of users who liked the post
      tags: ['NoAuth']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
        - $ref: '#/components/parameters/pathPostId'
      responses:
        '200':
          description: List of users who liked the post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameList'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
    put:
      operationId: addUserPostLike
      summary: Adds a like to the specified post
      tags: ['Authorization']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
        - $ref: '#/components/parameters/pathPostId'
      responses:
        '200':
          description: Like added correctly
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
    delete:
      operationId: removeUserPostLike
      summary: Remove a like to the specified post
      tags: ['Authorization']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
        - $ref: '#/components/parameters/pathPostId'
      responses:
        '200':
          description: Like removed correctly
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /users/{username}/feed/{post_id}/comments:
    get:
      operationId: getUserPostComments
      summary: Returns a list of comments under a post
      tags: ['NoAuth']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
        - $ref: '#/components/parameters/pathPostId'
      responses:
        '200':
          description: List of comments under the post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPostComment'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
    put:
      operationId: addUserPostComment
      summary: Adds a like to the specified post
      tags: ['Authorization']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
        - $ref: '#/components/parameters/pathPostId'
      responses:
        '200':
          description: Like added correctly
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
    delete:
      operationId: removeUserPostComment
      summary: Remove a like to the specified post
      tags: ['Authorization']
      parameters:
        - $ref: '#/components/parameters/pathUsername'
        - $ref: '#/components/parameters/pathPostId'
      responses:
        '200':
          description: Like removed correctly
        '400':
          $ref: '#/components/responses/400-InvalidRequest'
        '401':
          $ref: '#/components/responses/401-LoggedOut'
        '403':
          $ref: '#/components/responses/403-ForbiddenBanned'
        '404':
          $ref: '#/components/responses/404-ResourceNotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'

  /login:
    post:
      operationId: doLogin
      tags: [ "NoAuth" ]
      summary: Logs in the user
      description: |
        Logs in the user with the provided username.
        If the user does not exist, it will be created automatically.
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: Excale
                  pattern: '[a-zA-Z0-9_\-.]'
                  minLength: 3
                  maxLength: 20
      responses:
        '200':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "excale"

components:

  ##########################
  ## Parameter components ##
  ##########################
  parameters:

    pathUsername:
      name: username
      in: path
      required: true
      description: Username of the target user
      example: excale
      schema:
          $ref: '#/components/schemas/Username'

    pathPostId:
      name: post_id
      in: path
      required: true
      description: ID of the target post
      example: 9a6a4415-9a50-4065-b345-8c22e8bb8c5f
      schema:
          $ref: '#/components/schemas/UUID'

  #######################
  ## Schema components ##
  #######################
  schemas:

    UUID:
      type: string
      description: A UUID
      example: 9a6a4415-9a50-4065-b345-8c22e8bb8c5f
      format: uuid

    Username:
      type: string
      description: A user's username
      example: excale
      pattern: '[\w\d_\-.]+'
      minLength: 3
      maxLength: 20

    UsernameList:
      type: array
      description: A list of usernames
      items:
        $ref: '#/components/schemas/Username'

    UserProfile:
      type: object
      properties:
        username:
          $ref: '#/components/schemas/Username'
        display_name:
          type: string
          description: The user's display name.
          example: Emanuele Scaccia
        url_profile_picture:
          type: [ 'string', 'null' ]
          description: |-
            URL of the user's profile picture.
            Note: all photos are encoded with webp format.
            Generally, the url will be of the form
            `https://api.example.com/v1/users/{username}/assets/{photo_id}.webp`
          example: https://api.example.com/v1/users/excale/assets/3e270f31-6eaa-4418-ab97-7ed22f51d446.webp
        num_posts:
          type: number
          description: The number of posts the user has
          minimum: 0
          example: 4
        num_followers:
          type: number
          description: The number of followers the user has
          minimum: 0
          example: 123
        num_following:
          type: number
          description: The number of users the user is following
          minimum: 0
          example: 1234

    UserPost:
      type: object
      properties:
        id:
          type: string
          description: The uuid of the post.
          example: 3e270f31-6eaa-4418-ab97-7ed22f51d446
        username:
          type: string
          description: The username of the user who made the post.
          example: excale
        url_photo:
          type: string
          description: |-
            The URL of the photo. Note: all photos are encoded with webp format.
            Generally, the url will be of the form
            `https://api.example.com/v1/users/{username}/assets/{post_id}.webp`
          example: https://api.example.com/v1/users/excale/assets/3e270f31-6eaa-4418-ab97-7ed22f51d446.webp
        caption:
          type: [ 'string', 'null' ]
          description: The caption of the post.
          example: A day at the beach...
        num_likes:
          type: integer
          description: The number of likes the post has.
          example: 123
          minimum: 0
        num_comments:
          type: integer
          description: The number of comments the post has.
          example: 4
          minimum: 0
        timestamp:
          type: string
          description: The timestamp of the post, in `YYYY-MM-DD hh:mm:ss` format.
          example: 2021-01-01T00:00:00.000Z

    UserPostComment:
      type: object
      properties:
        id:
          type: string
          description: The uuid of the comment.
          example: 3e270f31-6eaa-4418-ab97-7ed22f51d446
        username:
          type: string
          description: The username of the user who added the comment.
          example: excale
        text:
          type: string
          description: The text of the comment.
          example: Nice photo!
        timestamp:
          type: string
          description: The timestamp of the comment, in `YYYY-MM-DD hh:mm:ss` format.
          example: 2021-01-01T00:00:00.000Z

    ResourceNotFoundException:
      type: object
      properties:
        message:
          type: string
          description: The message of the error.
          example: Couldn't find a user with the username 'excale'.
        type:
          type: string
          description: The type of the resource that doesn't exist.
          enum: ["user", "post", "comment"]
          example: user

  #########################
  ## Response components ##
  #########################
  responses:

    MonoUserPost:
      description: A post made by a user.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserPost'

    MultiUserPost:
      description: A list of posts made by one or more users.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserPost'

    MonoComment:
      description: A comment made by a user under a post.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserPost'

    MultiComment:
      description: A list of comments made by one or more users under a post.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserPost'

    200-Success:
      description: The operation was successful.

    400-InvalidRequest:
      description: The request was invalid or malformed (e.g. missing parameter).

    401-LoggedOut:
      description: The user is not logged in.

    403-Forbidden:
      description: The user is not allowed to perform the operation.

    403-ForbiddenBanned:
      description: The user has been banned by the specified user.

    404-ResourceNotFound:
      description: The specified user doesn't exist.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFoundException'

    500-InternalError:
      description: An internal error occurred.
